### ISSUE TITLE
GLIBC_2.32 not found error

### ISSUE THREAD

**Issue by lvotapka** [netscianalysis/netsci#17]
Hi @amstokely, I am having a problem running Netsci on a computer where I'm trying to test the manuscript's code before publishing. I've successfully installed all netsci software on this other machine, but when I run a Netsci calculation, I get the following error:

```
Traceback (most recent call last):
  File "/home/l1votapka/netsci_paper/netsci_paper/toy_systems/gaussian_computed_vs_exact_generate.py", line 8, in <module>
    import netcalc
  File "/home/l1votapka/miniconda3/envs/netsci/lib/python3.10/site-packages/netcalc-0.0.0-py3.10.egg/netcalc/__init__.py", line 5, in <module>
    from cuarray import FloatCuArray, IntCuArray
  File "/home/l1votapka/miniconda3/envs/netsci/lib/python3.10/site-packages/cuarray-0.0.0-py3.10.egg/cuarray/__init__.py", line 1, in <module>
    from .cuarray import FloatCuArray
  File "/home/l1votapka/miniconda3/envs/netsci/lib/python3.10/site-packages/cuarray-0.0.0-py3.10.egg/cuarray/cuarray.py", line 10, in <module>
    from . import _python_cuarray
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/l1votapka/netsci/cuarray/lib/libcuarray.so)
```

Notice that the problem occurs when netcalc is imported. Do I need to load a different version of CUDA? I've currently loaded cuda/11.8

**Comment by lvotapka** [comment]
@amstokely and I found out that I was attempting to use a GPU that is way too old - just for future reference if this problem is encountered.
